import "./globals.css";
import AuthContext from "./context/AuthContext";
import Header from "./Component/Header";
import BackgroundImage from "./Component/BackgroundImage";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-white h-screen">
        <AuthContext>
          <Header />
          <BackgroundImage />
          {children}
        </AuthContext>
      </body>
    </html>
  );
}
